[package]
name = "adventure_script"
version = "2.0.0-alpha.1"
authors = ["patataofcourse"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
thiserror = "1.0.30"
regex = "1.5.4"