[package]
name = "adventure_script"
version = "2.0.0-alpha.0"
authors = ["patataofcourse"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
thiserror = "1.0.30"