site_name: AdventureScript documentation
site_url: https://adventurescript.readthedocs.io/
nav:
  - Home: index.md
  - Getting started: start.md
  - Commands: commands.md
  - Configuration file: cfgfile.md
theme: readthedocs